### ISSUE TITLE
Window.build redundancy

### ISSUE THREAD

**Issue by random-person-001** [random-person-001/MagicText#1]
Parameters camX and camY are not used.  Is the necessary camera stuff done in ImageOrg.compileImage()?

**Comment by HazilTheNut** [comment]
That probably was an artifact of previous code being replaced with better ones. If it works it should be good.

**Comment by random-person-001** [comment]
So we can safely remove those parameters?

**Comment by random-person-001** [comment]
Fixed in ae7f702e
