### ISSUE TITLE
MULTIPLAYER

### ISSUE THREAD

**Issue by random-person-001** [random-person-001/MagicText#18]
So, there will inevitably be issues with introducing a fundamentally new way of the game running when it was originally designed for just one player.  Here are some issues I foresee:
- Room exit codes - the Server will have to handle each player more dynamically 
- Dialog texts - these will have to be bound to the player that opened them
- Dropped Items - these will have to stay alive after pickup and watch for pickup by any of the Players (even when there's none left who haven't taken it - more may enter the room)

I ( @random-person-001 ) shall be the primary worker on these, as the whole multiplayer functionality is my idea :smile:

**Comment by random-person-001** [comment]
Update:
I have uncommitted (ie unstable) code re: room switching/exit codes.  It may be a bit before I commit, unfortunately.

Dialog texts (and HUD) are pretty much taken care of now, as of 0ac99c876c26fadfcd0f23d6b3a5b80b1794b3f2

Currently, nothing has been done with dropped items.  Perhaps they could, rather than disappearing when there's a player above them, just dispense a copy of the item to them and remove a copy of their layer visible only to them, adding the player to an internal list of who's already picked it up.  <- Just some thoughts.  The item tracker thing may need to be modified for multiplayer if rooms are recreated each time, or be removed if rooms aren't.  _queue dramatic music of divisiveness over gameplay issue_

**Comment by random-person-001** [comment]
More things!
Dropped items now work - I implemented that idea in 365784d8410055a30a8d8430a5e8e99524d6ef2f

I committed the big ol' glump of stuff in b7f6389205adc0c9fdf1fbc8326950eb8debdcdb

**Comment by random-person-001** [comment]
Now it's pretty legit!  All that's left is a couple of bugs (like flashy display on player 1 when player 2 moves into a new room) to mop up, which I'll address individually!

Horray!

**Comment by zachllogan** [comment]
Also, we want to have LAN (or maybe even remote) play right? If not we should add different controls (WASD & IJKL | arrows) so they can be played at same time.

Also, so that I am familiar, how do items, enemies, & intractables work? And do we want to change that?
