### ISSUE TITLE
Death screen render errors & freezing

### ISSUE THREAD

**Issue by zachllogan** [random-person-001/MagicText#25]
The first times I died I got this rendering error when I was sent back to the main menu:

![menudeathglitch](https://cloud.githubusercontent.com/assets/22415468/19949744/7c6535a2-a121-11e6-8f37-2bde09537203.PNG)

when this happened I still could interact with main-menu items I just couldn't see them

Then I started getting this frozen screen:

![menudeathglitch2](https://cloud.githubusercontent.com/assets/22415468/19949745/7ec8c4c6-a121-11e6-8c99-77ce2bb1fdd6.PNG)

**Comment by random-person-001** [comment]
Erm, yeah.  Cleaning up after death is something we've kinda been neglecting...

**Comment by HazilTheNut** [comment]
We still have not a clue on how deaths are handled in multiplayer, so we
have put that on the back burner. As for now, you will just either not die
or restart the game if you do.

Also, the polar bear is a deadly enemy in Snowy Peak. Avoid if you feel as
if you die enough already.

**Comment by random-person-001** [comment]
Merging this bug with #14 
https://github.com/random-person-001/MagicText/issues/14
