### ISSUE TITLE
Switch Timers to better schedulers

### ISSUE THREAD

**Issue by zachllogan** [random-person-001/MagicText#27]
We should switch from using timers to using [ScheduledThreadPoolExecutor](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html) or [Quartz](http://www.quartz-scheduler.org/overview/features). Or maybe we could use Swing timers and/or replace some timers with listeners or loops.

**Comment by random-person-001** [comment]
Can one put listeners on random parts of the code, rather than UI things?  I hadn't thought of that.

**Comment by zachllogan** [comment]
I don't know, maybe? However, the listeners that you can put on UI components are probably more robust than you realize ([swing](https://docs.oracle.com/javase/tutorial/uiswing/events/api.html), [all](https://docs.oracle.com/javase/tutorial/uiswing/events/eventsandcomponents.html)). of particular interest to us might be [document listeners](https://docs.oracle.com/javase/tutorial/uiswing/events/documentlistener.html) and [property change lsiteners](https://docs.oracle.com/javase/tutorial/uiswing/events/propertychangelistener.html)(these seem to maybe be what you were wondering.)

either way I think we will probably need _some_ timers, I just don't think they should be used for everything (like player movement should just be a listener.)

There is also another option that requires no timers (or less). We could use a game-loop (or a few of them on different threads) that fires check&update methods.

**Comment by random-person-001** [comment]
Feel free to do this when you have some time; I think it'd be great.  I personally would be more in favor of using the builtin Java fuctionality over an external lib.  

_Unimportant Side Note_: the structure and inlineness of this Quartz sample code looks eerily like JavaScript (shudder):
![image](https://cloud.githubusercontent.com/assets/14933641/20162492/0b5f434e-a6bb-11e6-9734-f7da9261f9ff.png)

**Comment by random-person-001** [comment]
In 2991f46e651c306098ceb4767f313e8ca655791b, I switched the main menu (and multiplayer) to be event-driven by keys rather than looping on a timer, worth noting here I think.

**Comment by random-person-001** [comment]
Hey @zachllogan, what do you think of this now?  We've reduced cpu usage significantly on the rendering end of things.  I suspect a high proportion of the game still is in kernel mode; that would be nice to fix, I believe.  And it may be generally better practice to use normal threads rather than timers?  This should still be done, right?

**Comment by zachllogan** [comment]
I am not that familiar with code and CPU usage as it stands (between school and FTC I haven't had much time for the game), but I think if the CPU usage is within normal levels it isn't a major issue.

In general there could probably be some more clear and effective ways of doing things, so we might want to clean up the code, but if the issue is fixed, then it isn't terribly important. I think its most import that the code be written with these ideas in consideration from here on. Though cleaning up the code might help with that. Really what we want is modular code that is easily expandable and optimally light on resources (readability is always nice to.) So if their are ways to make the code more meet those goals, I think it might be worth the time to change it. Especially for modularity because not having to go back and modify old code much to add new features will make progress more efficient.

**Comment by random-person-001** [comment]
Ok.  I'll close this for now then.
