### ISSUE TITLE
Immersion

### ISSUE THREAD

**Issue by zachllogan** [random-person-001/MagicText#29]
The game as it stands is not very fun, and their are various reasons for this, like how short it is and the lack of things to do(which we have already discussed). This isn't really a problem yet because the game isn't terribly far along, but it will become one soon enough. One waywe can make the game more interesting is to increase immersion, this is especially important if the game is going to be story driven.

To increase immersion we should be adding NPC, landmarks, intteractability, things to be read, maybe even stores. The game right now feels dead. Let's bring it to life!

**Comment by random-person-001** [comment]
Man, you could almost be a politician with the flourish you ended with.  ;)

I put a poisonous berry that you can eat in the Room I'm working on (Cliffbottom - I may rename it later) that reduces your health.  To make the Player want it, I posted a rouge Bandit next to it. :)

There's also a hidden path in the forest that goes to a kiosk for Sen the Ultimate Tourist (a sideplot), and a user would never find it if they weren't looking.  We cold maybe drop some hints earlier in the game if we feel like it.

When I finish this level and feel eloquent or witty, I'll be on adding bits of text in earlier levels.  Good idea!

**Comment by random-person-001** [comment]
What do you guys (@zachllogan @HazilTheNut) think about trees becoming ash-grey and nonsolid if you shoot them with a fire spell?

I was working on this (close to done) and wanted to pass it by y'all.  My thoughts are that trees are rarely a critical element of a room, and if the user knows full well that they may be missing critical plot points by burning their own path around the obvious way, that's their decision, just like they can fly through text boxes or mess with the game through the HUD console if they ever find it.  More importantly, it gives freedom to the user in the game, which is meant to feel open and nonforced.

Also, trees are majorly featured in only two of the six or seven zones, and users only use fire spells roughly a fifth of the time, so they may not even discover this.

If I were the end user, I would greatly enjoy that bit of realism.

Approval?

**Comment by zachllogan** [comment]
Well, I'm not sure it should be possible to burn the game until no progression is possible, but I can't see harm in letting trees burn. So YES! Defiantly, that is exactly the sort of thing I was talking about with bringing the world to life! It should respond and interact with the user and make them feel as if it is a real world. That's the whole point of RPGs.

**Comment by zachllogan** [comment]
After we talked @random-person-001 , I was thinking about how the player should interact with NPCs. and I thought this is an RPG, so they should give quests, right? I don't know if that fits with the way the game would progress and the plot in your guys minds, but it would give the user things to do and direction. I was also thinking it would be cool to maybe have dialog response options (or even type in responses) that way the game world would feel more dynamic and the users would have more control over their experience (not to mention the opportunity for jokes; this is were many games put them). Fallout, STALKERS of Chernobyl , and Elder Scrolls: Oblivion are some good examples of dialog response systems.

Also another thing that would make the game world feel much more alive is random (and nonrandom) events.) Things like a traveling merchant is being attacked by bandits and you have to save him before it's to late, and maybe you have the option of siding with the bandits for a cut (maybe you even have the option to kill them all and take all their stuff for yours;) This could also include random encounters with mini-bosses; perhaps a shady dude in a back ally who gives "dark quests" that you have to not get caught while doing, or maybe he wants to sell you illegal or dubious items (a "potion" perhaps); a rare item (or creature that carries rare items) that they have to stop and work to get;a funny old gambling man that they can make bets of chance with; a rockslide/blizzard/thunderstorm/whatever; a pickpocket who steals one of your items and some money and then runs away, and the only way you can get your stuff back is to kill (or incapacitate?) him before he escapes(or maybe you can bump into him later wandering around town); mercenaries sent by the evil dude ambush, surround, and try to kill you; the wind or a tree decide to talk to you; a goat kicks you in the shin doing one damage; or whatever you can think of to spring a situation on the player.

speaking of towns the game doesn't have one does it. So while we are rethinking the plot maybe we should also rethink the maps; perhaps make them more expansive (single areas take about 10 seconds to walk through) and adding different types of area: friendly areas, like towns and villages and fairy caves; hostile areas, like fields and cliffs and dungeons; and neutral areas, places were you won't be attacked unless you provoke the attacker (by say getting caught braking into the theif's guild or something.) Maybe also exploration or puzzle areas where their is little or no living things, but just puzzles to solve or areas to find and explore.

what do you guys ( @HazilTheNut  @random-person-001 ) think about these ideas?

**Comment by random-person-001** [comment]
Questions were added in 90af71e29bfc31a200557f1d39591204826ce235 by @HazilTheNut! 

At the moment, we only have two towns slated to to be made throughout the game - a village in the Forest of Fondant and a port city where you get on a boat to cross the Sea of Surprise.

We'll be adding puzzles for sure - like in the Witch Hut.  It's hard to come up with ones, though.  Do you have ideas?

As for miniquests, I'm totally in favor!

**Comment by zachllogan** [comment]
Only 2 towns; hmm... that's rather few, especially considering their are 4 zones. Some games do very well without having (or having many) chatacters other than the protagonist, but those are rather few in numbers, so there should probably either be more towns/villages/congregations or their should be plenty of wanders to encounter.

Yeah puzzles are rather hard to come with, but it is easier to do when/if there are higher level graphics (have we decided on this yet?). I'll try to think some ideas up.

Miniquests yes, but also I was talking more about main quests. Even if they are not official ( get quest, complete it, turn it in, get rewarded) quests there should probably be someone who tells the character what they should (or maybe the character has internal dialogs, either way their should be dialog.) Plot in games is mostly delivered through dialog, so if we want a decent plot we need more of it (and RPGs are an especially dialog heavy genre of games.)

**Comment by random-person-001** [comment]
I think most of the content here was discussed by our meeting, so I'll close this issue to clean things up.
