### ISSUE TITLE
Enter Key Problems

### ISSUE THREAD

**Issue by quaris628** [random-person-001/MagicText#33]
## Enter key works for:
Starting the introduction
Starting a new game
Selecting join LAN game (and for all the LAN submenu)
Selecting Load Game and making the file browser pop up

Selecting Settings sub-menu
Selecting "controls" in the settings sub-menu
Mapping keys in the controls sub-sub-menu

Quitting the game
## Enter key does not work for:
going past the dialogue box after a new game is started
Selecting "main menu" in the settings sub-menu
Selecting "settings" at the bottom of the controls sub-sub-menu
## Also Note:
Using left and right arrows keys do nothing when "profile" is selected in the controls sub-sub-menu
The up and down arrow keys work just fine
Operating system = windows 10
## 
If you have any questions, please ask

**Comment by zachllogan** [comment]
I'm pretty sure they work fine. The enter key probably wasn't mapped to
continue for you (check under controls.) For left and right to do something
two conditions must be met:
1. The asterisk is next to "profile"
2. Their is more than one saved profile (check "./Settings/KeyMaps"). You
should be able to create a new keymap by typing in a name while "profile"
is selected, then hitting enter to save.

post if problem persists after checking those things (also make
sure to update.)

**Comment by zachllogan** [comment]
fixed. though beware the jar file may fall behind the current version

**Comment by quaris628** [comment]
To the previous error diagnosis:
Yes, I mapped the enter key to "continue/select". 
Yes, asterisk is next to "profile." I tried typing (which I hadn't before) and it did make text pop up on the screen. I don't know what it's supposed to do. Enter does nothing. Pressing left and right erases the name I typed from the screen, I can't get back to it. 
Yes, I have the files DEFAULT.STKM and NUM.STKM and WASD.STKM under Settings/KeyMaps

![image](https://cloud.githubusercontent.com/assets/25444836/22623381/c3ee5dda-eb1e-11e6-8acc-e4141df8b15d.png)

## After updating...

Controls sub-sub-menu is working fine! great!

After checking that the keymap profile is has enter mapped, I can start a new game! Thank you! 😄
